// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuPhEkPe5sDBjffytdsAs_ICU81AyLvP4',
    appId: '1:33815201789:web:1c93d0dcd51167c4',
    messagingSenderId: '33815201789',
    projectId: 'auto-connect-8',
    authDomain: 'auto-connect-8.firebaseapp.com',
    databaseURL: 'https://auto-connect-8.firebaseio.com',
    storageBucket: 'auto-connect-8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwAzPeVK6q5N0m6QPgIJRrtL8eghGZmy4',
    appId: '1:33815201789:android:b5e7cf606e896bd5ef3b94',
    messagingSenderId: '33815201789',
    projectId: 'auto-connect-8',
    databaseURL: 'https://auto-connect-8.firebaseio.com',
    storageBucket: 'auto-connect-8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjTN4gXCulJYB65nmSNUWyE6FYbldxQQs',
    appId: '1:33815201789:ios:042b6531b6a33c9eef3b94',
    messagingSenderId: '33815201789',
    projectId: 'auto-connect-8',
    databaseURL: 'https://auto-connect-8.firebaseio.com',
    storageBucket: 'auto-connect-8.appspot.com',
    androidClientId: '33815201789-ltrumbreo61uaouo394dpkuhsi9ovurh.apps.googleusercontent.com',
    iosClientId: '33815201789-agnq8cb4qiumcla5s1piau7iot90a4v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarTrashCan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjTN4gXCulJYB65nmSNUWyE6FYbldxQQs',
    appId: '1:33815201789:ios:042b6531b6a33c9eef3b94',
    messagingSenderId: '33815201789',
    projectId: 'auto-connect-8',
    databaseURL: 'https://auto-connect-8.firebaseio.com',
    storageBucket: 'auto-connect-8.appspot.com',
    androidClientId: '33815201789-ltrumbreo61uaouo394dpkuhsi9ovurh.apps.googleusercontent.com',
    iosClientId: '33815201789-agnq8cb4qiumcla5s1piau7iot90a4v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarTrashCan',
  );
}
